[project]
name = "pipecat-moss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cartesia>=2.0.17",
    "deepgram-sdk>=5.3.0",
    "inferedge-moss>=1.0.0b5",
    "pipecat-ai>=0.0.94",
]
